# Generated by Django 3.2.9 on 2021-12-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tone', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=10)),
                ('boat_docs', models.ImageField(blank=True, null=True, upload_to='BoatDocuments/')),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('no_of_containers', models.CharField(blank=True, max_length=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ship_docs', models.ImageField(blank=True, null=True, upload_to='ShipDocuments/')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('container_id', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(choices=[('40ft', '40ft'), ('20ft', '20ft')], default='40ft', max_length=200)),
                ('price', models.CharField(choices=[('112.5', '112.5'), ('65', '65')], default='112.5', max_length=200)),
                ('side', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Free', 'Free')], default='Pending', max_length=200)),
                ('comment', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ship.ship')),
            ],
        ),
    ]
