# Generated by Django 3.1.12 on 2021-12-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0017_alter_container_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='container',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
