# Generated by Django 3.1.12 on 2021-12-20 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0018_auto_20211220_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='boat_docs',
            field=models.FileField(blank=True, null=True, upload_to='BoatDocuments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='ship',
            name='ship_docs',
            field=models.FileField(blank=True, null=True, upload_to='ShipDocuments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='container',
            name='price',
            field=models.CharField(choices=[('112.5', '112.5'), ('62', '62')], default='112.5', max_length=200),
        ),
    ]
